// app/layout.tsx
import React, { ReactNode } from 'react';

export const metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
